### ISSUE TITLE
Windows Pip error

### ISSUE THREAD

**Issue by MTRNord** [aerkalov/ebooklib#104]
Windows Version 7 Service Pack 2
Python: Python 3.5.1
Pip: pip 8.1.2 from c:\users[USERNAME REMOVED]\appdata\local\programs\python\python35-32\lib\site-packages (python 3.5)
Error:

```
[NAME]@[NAME]-PC MINGW64 /m/github/Wattpad2Epub (master)
$ pip install ebooklib
Collecting ebooklib
  Using cached EbookLib-0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\[USERNAME REMOVED]\AppData\Local\Temp\pip-build-5vcrnd9o\ebooklib\setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "c:\users\[USERNAME REMOVED]\appdata\local\programs\python\python35-32\lib\encodings\cp1252.py", line 23, in decode
        return codecs.charmap_decode(input,self.errors,decoding_table)[0]
    UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1671: character maps to <undefined>

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\[USERNAME REMOVED]\AppData\Local\Temp\pip-build-5vcrnd9o\ebooklib\
```

I am unable to install this packet with pip. Is this caused by Python3?

**Comment by aerkalov** [comment]
Yes, something with encoding and Python 3. It has been fixed in the master branch in the repository, but "official" release has not been done and I did not uploaded it to pypi. Clone the repository from GitHub until i push it.

**Comment by pmlandwehr** [comment]
I'm [doing a source build](https://github.com/conda-forge/staged-recipes/pull/1262) using `conda` for [conda-forge](https://conda-forge.github.io) and have been seeing the same issue. Everything builds fine except for `python>=3.4 && win`, where I see the above error. I'm using all of the patches from the github repo, so I'm not sure that those are yet sufficient to fix this...

**Comment by sbadia** [comment]
Hi!
Same error here using python 3.5.2 on Ubuntu 16.04

```
root@01719149359c:~# python3 --version                                                                                                
Python 3.5.2
root@01719149359c:~# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial
root@01719149359c:~# pip3 install ebooklib
Collecting ebooklib
  Using cached EbookLib-0.15.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-kbah9l1c/ebooklib/setup.py", line 13, in <module>
        long_description = open('README.md').read(),
      File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc5 in position 1658: ordinal not in range(128)
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kbah9l1c/ebooklib
```
Any plan for the date of the next release?
Thanks in advance!

**Comment by streamliner18** [comment]
Hi, is there any word on this issue? It sure looks like the problem persists with Ubuntu 16 and Python 3.4.

**Comment by mark-saad** [comment]
Hey, I'm having the same issue on Windows 10 and Python 3.6

**Comment by aerkalov** [comment]
@mark-saad is it downloading Ebooklib-0.15 or  Ebooklib-0.16 for you? 0.16 should have this issue fixed because README file is not utf-8 anymore.

**Comment by vitormorales** [comment]
Hi! I'm having same issue too on Linux, Python 3.6 EbookLib 0.16.

**Comment by streamliner18** [comment]
@vitormorales It turns out that prepending `LC_ALL=C.UTF-8` fixes the issue on English-based linux systems anyhow. It's a default locale issue. On my Mac (which defaults to Unicode) this should never happen, though I'm not sure what LC translates to in Windows terms.

**Comment by mark-saad** [comment]
@aerkalov it's still downloading ebooklib-0.15 for me.

**Comment by aerkalov** [comment]
@mark-saad try "pip install --no-cache-dir ebooklib==0.16". Maybe pip has cached 0.15 version and does not want to download new one.

**Comment by tantale** [comment]
Hi, the PR #138 fix this issue.

Related to #132.
